// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNhkEu0yQWpQBpn-Wc8R_FnHqMRH54_tA',
    appId: '1:82601712779:web:c55ce2f395dd085c3f088e',
    messagingSenderId: '82601712779',
    projectId: 'deepgram-transcribe',
    authDomain: 'deepgram-transcribe.firebaseapp.com',
    storageBucket: 'deepgram-transcribe.appspot.com',
    measurementId: 'G-89RM9CFMYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXoI_RSYSyGDv38EDQF560ASXe1ZAHpyQ',
    appId: '1:82601712779:android:1fc7c443ca80f1a83f088e',
    messagingSenderId: '82601712779',
    projectId: 'deepgram-transcribe',
    storageBucket: 'deepgram-transcribe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-b8d-gD3tLctS7kVnPcXw7g2QJ_GAPlo',
    appId: '1:82601712779:ios:01719706b65b5aad3f088e',
    messagingSenderId: '82601712779',
    projectId: 'deepgram-transcribe',
    storageBucket: 'deepgram-transcribe.appspot.com',
    iosClientId: '82601712779-u7tkeecvkbfqoleo7ua4v298emvjp6md.apps.googleusercontent.com',
    iosBundleId: 'com.souvikbiswas.deepgramTranscribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-b8d-gD3tLctS7kVnPcXw7g2QJ_GAPlo',
    appId: '1:82601712779:ios:01719706b65b5aad3f088e',
    messagingSenderId: '82601712779',
    projectId: 'deepgram-transcribe',
    storageBucket: 'deepgram-transcribe.appspot.com',
    iosClientId: '82601712779-u7tkeecvkbfqoleo7ua4v298emvjp6md.apps.googleusercontent.com',
    iosBundleId: 'com.souvikbiswas.deepgramTranscribe',
  );
}
